### PR TITLE
Improve issues

### PR DESCRIPTION
**Pull request by haodaz**
Use number to order issue list, correct irregular cases, add en edition for "answer needed".

### CODE REVIEW

**Comment by haodaz** [comment]
A prototype of contribution tasks page.
Based on this page, I have reordered issues, separated English and Chinese issue versions, edited instructions in "about" page, and rewrote the QA card("Have questions? balabala") in each page.
image

**Comment by haodaz** [comment]
I also tried to fill the page structure with other covid numbers by editing index.yml
Screen Shot 2020-04-13 at 3 55 56 PM

**Comment by haodaz** [comment]
This is the final order of issue:
Screen Shot 2020-04-13 at 1 12 18 PM

**Comment by haodaz** [comment]
Handled all potential problems with "country balabala" before load HongKong data.

**Review by drumlab — APPROVED** [review]

**Pull request merged**
